[project]
name = "taskerapi"
version = "0.0.1"
authors = [
  { name="Lone Faerie", email="lone.faerie@gmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/lone-faerie/taskerapi"
"Bug Tracker" = "https://github.com/lone-faerie/taskerapi/issues"

[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"